# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    beta_version_number = "100"
    beta_groups = ["Internal Beta"]
    commit = last_git_commit
    
    lane :login do
        app_store_connect_api_key(
            key_id: "4UB5RCHV4V",
            issuer_id: "69a6de89-3298-47e3-e053-5b8c7c11a4d1",
            key_filepath: "~/.fastlane/keys/fastlane_4UB5RCHV4V.p8",
            duration: 1200, # optional (maximum 1200)
            in_house: false # optional but may be required if using match/sigh
        )
    end
    
    lane :beta do
        login
        
        increment_version_number_in_xcodeproj(version_number: beta_version_number)
        lb = latest_testflight_build_number
        increment_build_number(build_number: "#{lb + 1}")
        
        build_app(scheme: "Hosei-Sakai", xcargs: "-allowProvisioningUpdates") 
        upload_to_testflight(
            changelog: commit[:message],
            distribute_external: true,
            distribute_only: false,
            groups: beta_groups,
            reject_build_waiting_for_review: true
        )
    end
  
  lane :release do
        login
        
        lb = latest_testflight_build_number
        app_store_build_number
        lv = lane_context[SharedValues::LATEST_VERSION]
        increment_version_number_in_xcodeproj(version_number: lv)
        increment_version_number_in_xcodeproj(scheme: "Hosei-Sakai", bump_type: 'minor', omit_zero_patch_version: true)
        increment_build_number(build_number: "#{lb + 1}")
        
        build_app(scheme: "Hosei-Sakai", xcargs: "-allowProvisioningUpdates")
        upload_to_app_store(
	        skip_metadata: true, 
	        skip_screenshots: true, 
	        precheck_include_in_app_purchases: false
	    )
    end
end